$schema: http://json-schema.org/draft-07/schema#
title: Deploy Config
type: object

required:
  - dashboard_url
  - github_url
  - static_header_logo
  - static_light_logo
  - static_black_logo
  - static_dpg_white_logo
  - static_coronasafe_logo
  - gmaps_api_key
  - gov_data_api_key
  - recaptcha_site_key
  - kasp_enabled
  - kasp_string
  - kasp_full_string

properties:
  dashboard_url:
    type: string

  github_url:
    type: string

  static_header_logo:
    type: string

  static_light_logo:
    type: string

  static_black_logo:
    type: string

  static_dpg_white_logo:
    type: string

  static_coronasafe_logo:
    type: string

  gmaps_api_key:
    type: string

  gov_data_api_key:
    type: string

  recaptcha_site_key:
    type: string

  kasp_enabled:
    type: boolean

  kasp_string:
    type: string

  kasp_full_string:
    type: string

  state_logo:
    type: string

  state_logo_white:
    type: boolean
