name: Validate Configurations
on:
  - push
  - pull_request

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
      - run: npm ci
      - run: npm test
